# Generated by Django 6.0.3 on 2026-03-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='RDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('life_stage', models.CharField(choices=[('adult', 'Adult'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating'), ('child_1_3', 'Child 1-3 years'), ('child_4_8', 'Child 4-8 years'), ('child_9_13', 'Child 9-13 years'), ('adolescent_14_18', 'Adolescent 14-18 years')], max_length=20)),
                ('age_min', models.IntegerField(blank=True, help_text='Minimum age in years', null=True)),
                ('age_max', models.IntegerField(blank=True, help_text='Maximum age in years', null=True)),
                ('energy_kcal', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('iron_mg', models.FloatField(default=0)),
                ('calcium_mg', models.FloatField(default=0)),
                ('vitamin_a_rae_ug', models.FloatField(default=0)),
                ('folate_ug', models.FloatField(default=0)),
                ('vitamin_c_mg', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('zinc_mg', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'RDA',
                'verbose_name_plural': 'RDAs',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kfct_code', models.CharField(blank=True, max_length=20, null=True)),
                ('food_name', models.CharField(max_length=255)),
                ('energy_kcal', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('carbohydrate_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('water_g', models.FloatField(default=0)),
                ('ash_g', models.FloatField(default=0)),
                ('calcium_mg', models.FloatField(default=0)),
                ('iron_mg', models.FloatField(default=0)),
                ('magnesium_mg', models.FloatField(default=0)),
                ('phosphorus_mg', models.FloatField(default=0)),
                ('potassium_mg', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('zinc_mg', models.FloatField(default=0)),
                ('copper_mg', models.FloatField(default=0)),
                ('manganese_mg', models.FloatField(default=0)),
                ('selenium_ug', models.FloatField(default=0)),
                ('vitamin_a_rae_ug', models.FloatField(default=0)),
                ('thiamin_mg', models.FloatField(default=0)),
                ('riboflavin_mg', models.FloatField(default=0)),
                ('niacin_mg', models.FloatField(default=0)),
                ('vitamin_b6_mg', models.FloatField(default=0)),
                ('folate_ug', models.FloatField(default=0)),
                ('vitamin_b12_ug', models.FloatField(default=0)),
                ('vitamin_c_mg', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.category')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('grams', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='foods.food')),
            ],
            options={
                'unique_together': {('food', 'unit_name')},
            },
        ),
    ]
