# Generated by Django 6.0.3 on 2026-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rda',
            name='life_stage',
            field=models.CharField(choices=[('infant', 'Infant (0-12 months)'), ('child_1_3', 'Child 1-3 years'), ('child_4_8', 'Child 4-8 years'), ('child_9_13', 'Child 9-13 years'), ('adolescent_14_18', 'Adolescent 14-18 years'), ('adult', 'Adult'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating')], max_length=20),
        ),
    ]
