# Generated by Django 6.0.3 on 2026-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_rda_life_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rda',
            name='age_max',
            field=models.FloatField(blank=True, help_text='Maximum age in years (use 0.5 for 6 months)', null=True),
        ),
        migrations.AlterField(
            model_name='rda',
            name='age_min',
            field=models.FloatField(blank=True, help_text='Minimum age in years (use 0.5 for 6 months)', null=True),
        ),
    ]
