# Generated by Django 6.0.3 on 2026-03-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_rda_age_max_alter_rda_age_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Meal categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('person_name', models.CharField(blank=True, max_length=100)),
                ('person_age', models.IntegerField(blank=True, null=True)),
                ('person_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount in grams')),
                ('unit', models.CharField(default='grams', max_length=50)),
                ('grams', models.FloatField(help_text='Actual grams consumed')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.mealcategory')),
                ('meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.mealrecord')),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.IntegerField(help_text='Amount in milliliters')),
                ('time', models.TimeField(auto_now_add=True)),
                ('meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.mealrecord')),
            ],
        ),
    ]
