# Generated by Django 6.0.3 on 2026-03-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_mealcategory_mealrecord_mealfooditem_waterintake'),
    ]

    operations = [
    ]
