# Generated by Django 6.0.3 on 2026-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol_mg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='monounsaturated_fat_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='polyunsaturated_fat_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat_g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar_g',
            field=models.FloatField(default=0),
        ),
    ]
